# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 关于
    url: '#about'
    weight: 10
    

  - name: 汇总        #Posts
    url: 
    weight: 20
    
  - name: 日常笔记
    parent: 汇总
    url: '#posts'
    weight: 21
      
  - name: 科研软件
    parent: 汇总
    url: 'software'
    weight: 22
      
  - name: 网页工具
    parent: 汇总
    url:
    weight: 23
      
  - name: 办公
    parent: 汇总
    url: 
    weight: 24
      
  - name: 图片工具
    parent: 汇总
    url: 
    weight: 25
      
  - name: 跑步
    parent: 汇总
    url: 
    weight: 26
    
    
  - name: 点滴生活         #Projects
    url: '#projects'
    weight: 30
    
  - name: 基因组下载        #talks
    url: 
    weight: 40
  - name: 小麦基因组
    parent: 基因组下载
    url: 'genome'
    weight: 41
  - name: 条锈菌基因组
    parent: 基因组下载
    url: 'pst'
    weight: 42




  - name: 已发表文章     #featured
    url: "publication"
    weight: 50
    
#  - name: Gallery     
#    url: '#Gallery'     
#    weight: 60
    
  - name: 微信公众号
    url: wechat/
    weight: 70
  - name: 博客
    url: 'https://gswechatarticle.netlify.app/'
    weight: 80
